=== Jenkins Guide

''''

==== 1. Jenkins Installation

===== 1.1 Debian packages "Ubuntu/Debian"
----
$ wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
----
----
$ sudo nano /etc/apt/sources.list
# add the following entry:
deb http://pkg.jenkins-ci.org/debian binary/
----
----
$ sudo apt-get update
$ sudo apt-get install jenkins
----
Individual Package Downloads: +http://pkg.jenkins-ci.org/debian/+

===== 1.2 RedHat Linux RPM packages "RedHat/Fedora/CentOS"
----
$ sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
$ sudo rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
----
----
$ yum install jenkins
----
Individual Package Downloads: +http://pkg.jenkins-ci.org/redhat//+

===== 1.3 openSUSE Linux RPM packages
----
$ sudo zypper addrepo http://pkg.jenkins-ci.org/opensuse/ jenkins
----
----
$ zypper install jenkins
----
Individual Package Downloads: +http://pkg.jenkins-ci.org/opensuse/+

===== 1.4 Up-/Downgrade
Upgrade to v1.514 in an "Ubuntu 12.04 LTS" environment

you can find the war file here: +http://mirrors.jenkins-ci.org/war/+

----
$ cd /user/share/jenkins/
$ sudo rm -rf jenkins.war
$ sudo wget http://mirrors.jenkins-ci.org/war/1.514/jenkins.war
----
----
$ /etc/init.d/jenkins restart
----

===== 1.5 Start the JenkinsServer
----
$ sudo service jenkins start
----

_After a successful installation you can access the JenkinsServer in your browser on:_ +http://localhost:8080+

''''

==== 2. Jenkin PlugIns Installation

Went to +http://localhost:8080/pluginManager/available+ and "check" the wanted PlugIns for installation.

The Jenkins PlugIns are here listed: +https://wiki.jenkins-ci.org/display/JENKINS/Plugins+


''''

==== 3. Configure Jenkins

*TODO!!!*

''''

==== 4. Configure PlugIns

*TODO!!!*

''''

==== 5. Configure Cob-Pipeline

*TODO!!!*

''''

==== 6. Configure Git

Set up the GitHub user.
This user has to have read-access to all repositories to build and write-access to your jenkins_config repository.
----
$ git config --global user.name "<USER_NAME>"
$ git config --global user.email "<EMAIL>"
----

''''

==== 7. Configure SSH

A .ssh-folder is needed inside the jenkins-config folder which contains a ssh-key to access the GitHub-repositories.
Either you generate a new key with ssh-keygen or you just copy the .ssh of the master.
You have to add this key to your GitHub user (http://github.com/settings/ssh).
This user should have read-access to all repositories you want to build.
It is very important that 'github.com' belongs to the known hosts.
Therefore the .ssh-folder should contain a known_hosts file.
Whether 'github.com' is already known can be checked by entering:
----
$ ssh-keygen -H -f <known_hosts_PATH> -F github.com
----

If it is not known, you can add 'github.com' to the known_hosts by entering:
----
$ ssh-keyscan -H github.com > <known_hosts_PATH>
----

Furthermore the Jenkins masters SSH key itself has to be an authorized one.

''''

==== 8. The Jenkins Repository

===== 8.1 jenkins_config repository
----
$ git clone git@github.com:ipa320/jenkins_config.git ~/jenkins-config/jenkins_config
----

===== 8.2 jenkins_setup repository
----
$ git clone git@github.com:ipa320/jenkins_setup.git ~/jenkins-config/jenkins_setup
----

===== 8.2.1 Adapt apt-cacher address

If you use an apt-cacher you have to enter its address in the install_basics.sh script.
Adapt the APT_PROXY_ADDRESS variable to your requirements.

The Script: +https://github.com/ipa320/jenkins_setup/blob/master/scripts/install_basics.sh+

----
$ echo "\n***APT-PROXY***"
$ APT_PROXY_ADDRESS="http://cob-jenkins-server:3142"
$ sh -c 'echo "Acquire::http { Proxy \"'$APT_PROXY_ADDRESS'\"; };" > /etc/apt/apt.conf.d/01proxy'
----

===== 8.2.2 PYTHONPATH
----
$ echo "export PYTHONPATH=~/jenkins-config/jenkins_setup/src" > /etc/profile.d/python_path.sh
$ echo "source /opt/ros/<ROS_RELEASE>/setup.sh" >> /etc/profile.d/python_path.sh
----

''''

==== 9. MailerTemplate

Standart MailerTemplate Folder is:
----
$ cd /var/lib/jenkins/email-templates/
----
Save all your MailerTemplates in this folder

This is how MailerTemplates looks like: +https://github.com/ipa320/jenkins_setup/blob/master/templates/email-templates/html-with-health-builds-tests.jelly+

''''

==== 10. Tarball Server
----
$ mkdir -p ~/chroot_tarballs/in_use_on__<JENKINS_MASTER_NAME>
----

''''

==== 11. Slave Configuration

===== 11.1 Sudo commands without password

===== 11.2 SSH access without password

===== 11.3 Pbuilder

===== 11.4 

*TODO!!!*

''''

==== 12. The Pipeline

*TODO!!!*

''''














