=== Jenkins Guide

''''

==== 1. Prerequisites

===== 1.1 Operating System
Install the Operating System of your choice for your Server.

Supported OS are:
Windows
- Ubuntu/Debian
- Red Hat/Fedora/CentOS
- Mac OS X
- openSUSE
- FreeBSD
- OpenBSD
- Solaris/OpenIndiana
- Gentoo

This Guide proceed for an Ubuntu 12.04 "LTS" environment...

===== 1.2 Robotic Operating System

===== 1.2.1 Install ROS "fuerte" and "groovy"
----
$ sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
$ wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
$ sudo apt-get update
----
----
$ sudo apt-get install ros-fuerte-desktop-full
$ sudo apt-get install ros-groovy-desktop-full
----
----
$ sudo rosdep init
$ rosdep update
----

===== 1.2.2 Environment setup
----
# for fuerte
$ echo "source /opt/ros/fuerte/setup.bash" >> ~/.bashrc
$ source ~/.bashrc
----
----
# for groovy
$ echo "source /opt/ros/groovy/setup.bash" >> ~/.bashrc
$ source ~/.bashrc
----
if you just want to change the environment of your current shell, you can type:
----
# for fuerte
$ source /opt/ros/fuerte/setup.bash
----
----
# for groovy
$ source /opt/ros/groovy/setup.bash
----

===== 1.2.3 Install additional tools
----
$ sudo apt-get install python-rosinstall python-rosdep
$ sudo apt-get install python-setuptools ogre-tools ros-groovy-diagnostics-monitors
$ sudo apt-get install ros-groovy-rxtools ros-groovy-pr2-* ros-groovy-client-rosjava-jni
$ sudo apt-get install ros-groovy-openni*
----

===== 1.3 Java Runtime Environment
===== 1.3.1 Check your Java Version:
----
$ java -version
----
_Output example:_
----
java version "1.6.0_35"
Java(TM) SE Runtime Environment (build 1.6.0_35-b10)
Java HotSpot(TM) Client VM (build 20.10-b01, mixed mode, sharing)
----

===== 1.3.2 Install Java6
----
$ sudo apt-get install openjdk-6-jre
$ sudo apt-get install openjdk-6-jdk openjdk-6-source openjdk-6-doc openjdk-6-jre-headless openjdk-6-jre-lib 
----

===== 1.3.4 Install Java7
----
$ sudo apt-get install openjdk-7-jre
$ sudo apt-get install openjdk-7-jdk openjdk-7-source openjdk-7-doc openjdk-7-jre-headless openjdk-7-jre-lib
----

===== 1.4 Git
----
$ sudo apt-get install git-core
----

===== 1.5 Maven
----
$ sudo apt-get update && sudo apt-get install maven
----

''''

==== 2. Jenkins Installation

Define standart directories:
----
$ export JENKINS_BASE=/usr/local/jenkins
$ export JENKINS_HOME=/var/jenkins-data
$ java -jar ${JENKINS_BASE}/jenkins.war
----

===== 2.1 Debian packages "Ubuntu/Debian"
----
$ wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
$ sudo echo "deb http://pkg.jenkins-ci.org/debian binary/" > /etc/apt/sources.list.d/jenkins.list
----
----
$ sudo apt-get update && sudo apt-get install -y jenkins
----

Individual Package Downloads: +http://pkg.jenkins-ci.org/debian/+

===== 2.2 Up and Downgrade
Upgrade to v1.514

You can find the war file here: +http://mirrors.jenkins-ci.org/war/+

----
$ cd /user/share/jenkins/
$ sudo rm -rf jenkins.war
$ sudo wget http://mirrors.jenkins-ci.org/war/1.514/jenkins.war
----
----
$ /etc/init.d/jenkins restart
----

===== 2.3 Start and stop the Jenkins-Server
----
$ /etc/init.d/jenkins stop
$ /etc/init.d/jenkins start
----

After a successfull installation you can access the Jenkins-Server in your browser: +http://localhost:8080+

''''

==== 3. Jenkins Configuration

===== 3.1 

''''

==== 4. Jenkins-PlugIns Installation

Went to +http://localhost:8080/pluginManager/available+ and "check" the wanted PlugIns for installation.

For more information visit the Jenkins Wiki for PlugIns: +https://wiki.jenkins-ci.org/display/JENKINS/Plugins+


''''

==== Master Configuration

''''

==== Slave Configuration

''''

==== IPA Configuration

''''
