=== Jenkins Guide

''''

==== 1. Prerequisites

===== 1.1 Operating System
Install the Operating System of your choice for your Server.

===== 1.2 Robotic Operating System
Install ROS. You can find the Guide here: ++

===== 1.3 Java Runtime Environment
===== 1.3.1 Check your Java Version:
----
$ java -version
----
*Output example:*
----
java version "1.6.0_35"
Java(TM) SE Runtime Environment (build 1.6.0_35-b10)
Java HotSpot(TM) Client VM (build 20.10-b01, mixed mode, sharing)
----

===== 1.3.2 Find out your System-Architecture:
----
$ lscpu | grep Architecture
----
*Output example:*
----
Architecture:          x86_64 (= 64-Bit)
----

===== 1.3.3 Install Java 6 JRE


===== 1.4 Git

''''

==== 2. Jenkins Installation

===== 2.1 Debian packages "Ubuntu/Debian"
----
$ wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
----
----
$ sudo nano /etc/apt/sources.list
# add the following entry:
deb http://pkg.jenkins-ci.org/debian binary/
----
----
$ sudo apt-get update
$ sudo apt-get install jenkins
----
Individual Package Downloads: +http://pkg.jenkins-ci.org/debian/+

===== 2.2 RedHat Linux RPM packages "RedHat/Fedora/CentOS"
----
$ sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
$ sudo rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
----
----
$ yum install jenkins
----
Individual Package Downloads: +http://pkg.jenkins-ci.org/redhat//+

===== 2.3 openSUSE Linux RPM packages
----
$ sudo zypper addrepo http://pkg.jenkins-ci.org/opensuse/ jenkins
----
----
$ zypper install jenkins
----
Individual Package Downloads: +http://pkg.jenkins-ci.org/opensuse/+

===== 2.4 Up-/Downgrade
Upgrade to v1.514 in an "Ubuntu 12.04 LTS" environment

you can find the war file here: +http://mirrors.jenkins-ci.org/war/+

----
$ cd /user/share/jenkins/
$ sudo rm -rf jenkins.war
$ sudo wget http://mirrors.jenkins-ci.org/war/1.514/jenkins.war
----
----
$ /etc/init.d/jenkins restart
----

===== 2.5 Start and stop the Jenkins Server
----
$ /etc/init.d/jenkins stop
$ /etc/init.d/jenkins start
----

_After a successful installation you can access the JenkinsServer in your browser on:_ +http://localhost:8080+

''''

==== 3. Configure the Jenkins Server

*TODO!!!*

''''

==== 4. Jenkins PlugIns Installation

Went to +http://localhost:8080/pluginManager/available+ and "check" the wanted PlugIns for installation.

For more information visit the Jenkins Wiki for PlugIns: +https://wiki.jenkins-ci.org/display/JENKINS/Plugins+


''''

==== Master Configuration

''''

==== Slave Configuration

''''
